name: PyInstaller

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
     - dev

permissions:
  contents: read

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    needs: build-linux
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install pip -U
        pip install pyinstaller transliterate -U
        pip install -r requirements.txt -U
    - name: Build with pyinstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --add-data "lang.json;." --add-data "serverrating.json;." --add-data "icons;icons\" --collect-all transliterate --name msms main.py
    - name: Upload bundled file
      uses: actions/upload-artifact@v3
      with:
        name: msms-windows.exe
        path: dist/msms.exe
        if-no-files-found: error
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install pip -U
        pip install pyinstaller transliterate flake8 -U
        pip install -r requirements.txt -U
    - name: Python Syntax Checker
      run: |
        flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
    - name: Build with pyinstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --add-data lang.json:. --add-data serverrating.json:. --add-data icons:icons/ --collect-all transliterate --name msms main.py
    - name: Upload bundled file
      uses: actions/upload-artifact@v3
      with:
        name: msms-linux
        path: dist/msms
        if-no-files-found: error
